const React = require("react");
const ReactDOM = require("react-dom");

class Criteria extends React.Component {
    render() {
	return <li>{this.props.text}</li>;
    }
}

class CriteriaList extends React.Component {
    constructor(props) {
	super(props);

	// TODO: get this from the db
	this.state = {
	    criteria: [
		"All Videos submitted must be original content, remixed content is permitted if it does not infringe any copyrights.",
		"Traditional music videos and live performance videos will be accepted.",
		"Videos may be submitted by any member of the team that created them.",
		"Content contributors must be able to demonstrate the ownership and right to distribute the video on the internet to a worldwide audience.",
		"There is no minimum or maxiumum length for the videos.",
		"videos must be in high definition (minimum 720p, preferred 1080p).",
		"Multiple submissions are allowed.",
		"For each video you submit, you grant notTV a non-exclusive, worldwide electronic distribution license to stream the video on www.not.tv or any of the websites owned by notTV, anywhere in the world, electronically, in perpituity.",
		"All money after expenses, generated by the operations of notTV, is distributed to the member-owners of notTV.",
		"You must be a notTV member for your content to be eligible for commercial revenue generation."
	    ]
	};
    }
    
    render(){
	return(
	    <div id="subCrit">
	      <h1>Video Submission Criteria</h1>
	      <ol>
		{this.state.criteria.map((c, idx)=><Criteria key={idx} text={c}/>)}
	    </ol>
		</div>
	);
    }
}

ReactDOM.render(<CriteriaList />, document.getElementById('rootRight'));
